# Server Configuration
server.port=8085

# Application Configuration
spring.application.name=aroma-store-bff

# Feign Client Configuration
spring.cloud.openfeign.httpclient.enabled=true

# Logging Configuration
logging.level.com.aromastore.bff.client=DEBUG
